CREATE TABLE [||PRE||mmc_cart] ([cartID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[dateCreate] DATETIME NOT NULL  DEFAULT NULL  ,[dateLastUpdate] DATETIME NOT NULL  DEFAULT NULL  ,[isProcessed] SMALLINT NULL  DEFAULT 0 ,[isSaved] SMALLINT NULL  DEFAULT 0 ,[isCompleted] SMALLINT NULL  DEFAULT 0 ,[isPending] SMALLINT NULL  DEFAULT 0 ,[isActive] SMALLINT NULL  DEFAULT 0 ,[datePending] DATETIME NULL  DEFAULT NULL  ,[tempUserID] NVARCHAR(35) NULL  DEFAULT NULL  ,[userID] NVARCHAR(35) NULL  DEFAULT NULL  ,[remoteID] NVARCHAR(35) NULL  DEFAULT NULL  ,[attributes] NTEXT NULL  DEFAULT NULL  ,[siteID] VARCHAR(25) NOT NULL  DEFAULT NULL  ,CONSTRAINT [||PRE||mmc_cart_mmc_cart_ms_cart_PRIMARY]  PRIMARY KEY  CLUSTERED  ([cartID])); 
 CREATE  INDEX [||PRE||mmc_cart_mmc_cart_ms_cart_idxExpiry] ON [||PRE||mmc_cart] ([isActive],[isCompleted],[isPending],[isProcessed],[isSaved],[dateLastUpdate]);
 CREATE  INDEX [||PRE||mmc_cart_mmc_cart_ms_cart_idxLastUpdate] ON [||PRE||mmc_cart] ([dateLastUpdate]);
 CREATE  INDEX [||PRE||mmc_cart_mmc_cart_ms_cart_idxRemoteID] ON [||PRE||mmc_cart] ([remoteID]);
 CREATE  INDEX [||PRE||mmc_cart_mmc_cart_ms_cart_idxuserID] ON [||PRE||mmc_cart] ([userID]);

CREATE TABLE [||PRE||mmc_cartproduct] ([cartProductID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[cartID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[productID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[dateCreate] DATETIME NOT NULL  DEFAULT NULL  ,[dateLastUpdate] DATETIME NOT NULL  DEFAULT NULL  ,[moduleID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[price] DECIMAL NOT NULL  DEFAULT 0 ,[quantity] INT NOT NULL  DEFAULT NULL  ,[remoteID] NVARCHAR(35) NULL  DEFAULT NULL  ,[attributes] NTEXT NULL  DEFAULT NULL  ,[attributesID] NVARCHAR(35) NULL  DEFAULT NULL  ,[tax] DECIMAL NULL  DEFAULT 0 ,[shipping] DECIMAL NULL  DEFAULT 0 ,[discount] DECIMAL NULL  DEFAULT 0 ,CONSTRAINT [||PRE||mmc_cartproduct_mmc_cartproduct_ms_cartproduct_PRIMARY]  PRIMARY KEY  CLUSTERED  ([cartProductID])); 
 CREATE  INDEX [||PRE||mmc_cartproduct_mmc_cartproduct_ms_cartproduct_idxcartID] ON [||PRE||mmc_cartproduct] ([cartID]);
 CREATE  INDEX [||PRE||mmc_cartproduct_mmc_cartproduct_ms_cartproduct_idxproductID] ON [||PRE||mmc_cartproduct] ([productID],[attributesID]);
 CREATE  INDEX [||PRE||mmc_cartproduct_mmc_cartproduct_ms_cartproduct_idxRemoteID] ON [||PRE||mmc_cartproduct] ([remoteID]);

CREATE TABLE [||PRE||mmc_display] ([displayID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[displayTypeID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[objectID] NVARCHAR(35) NULL  DEFAULT NULL  ,[name] VARCHAR(150) NOT NULL  DEFAULT NULL  ,[dateCreate] DATETIME NOT NULL  DEFAULT NULL  ,[dateLastUpdate] DATETIME NOT NULL  DEFAULT NULL  ,[siteID] VARCHAR(25) NOT NULL  DEFAULT NULL  ,[params] NTEXT NULL  DEFAULT NULL  ,[notes] NTEXT NULL  DEFAULT NULL  ,[isActive] SMALLINT NULL  DEFAULT 0 ,[adminID] NVARCHAR(35) NULL  DEFAULT NULL  ,[moduleID] NVARCHAR(35) NULL  DEFAULT NULL  ,[contentID] NVARCHAR(35) NULL  DEFAULT NULL  ,[isValid] SMALLINT NULL  DEFAULT 0 ,[settings] NTEXT NULL  DEFAULT NULL  ,CONSTRAINT [||PRE||mmc_display_mmc_display_ms_display_PRIMARY]  PRIMARY KEY  CLUSTERED  ([displayID])); 

CREATE TABLE [||PRE||mmc_displaytype] ([displaytypeid] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[objectID] NVARCHAR(35) NULL  DEFAULT NULL  ,[package] VARCHAR(45) NOT NULL  DEFAULT NULL  ,[name] VARCHAR(45) NOT NULL  DEFAULT NULL  ,[description] NTEXT NULL  DEFAULT NULL  ,[settings] NTEXT NULL  DEFAULT NULL  ,[isConfigurable] SMALLINT NOT NULL  DEFAULT 0 ,[isActive] SMALLINT NOT NULL  DEFAULT 0 ,[version] VARCHAR(12) NOT NULL  DEFAULT NULL  ,[defaults] NTEXT NULL  DEFAULT NULL  ,[moduleID] NVARCHAR(35) NULL  DEFAULT NULL  ,CONSTRAINT [||PRE||mmc_displaytype_mmc_displaytype_ms_displaytype_PRIMARY]  PRIMARY KEY  NONCLUSTERED  ([displaytypeid])); 

CREATE TABLE [||PRE||mmc_location] ([locationID] BIGINT IDENTITY(1,1) ,[name] VARCHAR(150) NOT NULL  DEFAULT NULL  ,[value] VARCHAR(150) NOT NULL  DEFAULT NULL  ,[locationType] VARCHAR(15) NOT NULL  DEFAULT NULL  ,[orderNo] BIGINT NOT NULL  DEFAULT 0 ,CONSTRAINT [||PRE||mmc_location_mmc_location_PK_mmc_location]  PRIMARY KEY  CLUSTERED  ([locationID])); 
 CREATE  INDEX [||PRE||mmc_location_mmc_location_ms_location_idx_type] ON [||PRE||mmc_location] ([locationType],[orderNo]);

CREATE TABLE [||PRE||mmc_merchant] ([merchantID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[name] VARCHAR(100) NOT NULL  DEFAULT NULL  ,[isActive] SMALLINT NOT NULL  DEFAULT 0 ,[custom1label] VARCHAR(50) NULL  DEFAULT NULL  ,[custom2label] VARCHAR(50) NULL  DEFAULT NULL  ,[custom3label] VARCHAR(50) NULL  DEFAULT NULL  ,[remoteID] NVARCHAR(35) NULL  DEFAULT NULL  ,[package] VARCHAR(50) NOT NULL  DEFAULT NULL  ,[bean] VARCHAR(250) NOT NULL  DEFAULT NULL  ,[param1label] VARCHAR(50) NULL  DEFAULT NULL  ,[param2label] VARCHAR(50) NULL  DEFAULT NULL  ,[param3label] VARCHAR(50) NULL  DEFAULT NULL  ,[param4label] VARCHAR(50) NULL  DEFAULT NULL  ,[param5label] VARCHAR(50) NULL  DEFAULT NULL  ,[param6label] VARCHAR(50) NULL  DEFAULT NULL  ,[param7label] VARCHAR(50) NULL  DEFAULT NULL  ,[param8label] VARCHAR(50) NULL  DEFAULT NULL  ,[param9label] VARCHAR(50) NULL  DEFAULT NULL  ,[param1] VARCHAR(250) NULL  DEFAULT NULL  ,[param2] VARCHAR(250) NULL  DEFAULT NULL  ,[param3] VARCHAR(250) NULL  DEFAULT NULL  ,[param4] VARCHAR(250) NULL  DEFAULT NULL  ,[param5] VARCHAR(250) NULL  DEFAULT NULL  ,[param6] VARCHAR(250) NULL  DEFAULT NULL  ,[param7] VARCHAR(250) NULL  DEFAULT NULL  ,[param8] VARCHAR(250) NULL  DEFAULT NULL  ,[param9] VARCHAR(250) NULL  DEFAULT NULL  ,[params] NTEXT NULL  DEFAULT NULL  ,[isCurrent] SMALLINT NOT NULL  DEFAULT 0 ,CONSTRAINT [||PRE||mmc_merchant_mmc_merchant_ms_merchant_PRIMARY]  PRIMARY KEY  NONCLUSTERED  ([merchantID])); 

CREATE TABLE [||PRE||mmc_paymenttype] ([paymentTypeID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[name] VARCHAR(100) NOT NULL  DEFAULT NULL  ,[identity] VARCHAR(25) NOT NULL  DEFAULT NULL  ,[remoteID] NVARCHAR(35) NULL  DEFAULT NULL  ,[isActive] SMALLINT NOT NULL  DEFAULT 0 ,[params] NTEXT NULL  DEFAULT NULL  ,[paymentType] VARCHAR(25) NOT NULL  DEFAULT N'card' ,CONSTRAINT [||PRE||mmc_paymenttype_mmc_paymenttype_ms_paymenttype_PRIMARY]  PRIMARY KEY  CLUSTERED  ([paymentTypeID])); 
 CREATE  INDEX [||PRE||mmc_paymenttype_mmc_paymenttype_ms_paymenttype_identity] ON [||PRE||mmc_paymenttype] ([identity]);

CREATE TABLE [||PRE||mmc_transaction] ([transactionID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[total] DECIMAL NULL  DEFAULT 0 ,[dateCreate] DATETIME NOT NULL  DEFAULT NULL  ,[dateLastUpdate] DATETIME NOT NULL  DEFAULT NULL  ,[cartID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[cardLastFour] NVARCHAR(4) NOT NULL  DEFAULT N'xxxx' ,[cardMonth] SMALLINT NOT NULL  DEFAULT 0 ,[cardYear] BIGINT NOT NULL  DEFAULT 0 ,[isCompleted] SMALLINT NOT NULL  DEFAULT 0 ,[isApproved] SMALLINT NOT NULL  DEFAULT 0 ,[approvalCode] VARCHAR(45) NULL  DEFAULT NULL  ,[errorCode] VARCHAR(45) NULL  DEFAULT NULL  ,[custom1] VARCHAR(250) NULL  DEFAULT NULL  ,[custom2] VARCHAR(250) NULL  DEFAULT NULL  ,[custom3] VARCHAR(250) NULL  DEFAULT NULL  ,[remoteID] NVARCHAR(35) NULL  DEFAULT NULL  ,[params] NTEXT NULL  DEFAULT NULL  ,[tax] DECIMAL NULL  DEFAULT 0 ,[shipping] DECIMAL NULL  DEFAULT 0 ,[discount] DECIMAL NULL  DEFAULT 0 ,[subtotal] DECIMAL NULL  DEFAULT 0 ,[paymentTypeID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[merchantID] NVARCHAR(35) NULL  DEFAULT NULL  ,[orderIdent] VARCHAR(20) NULL  DEFAULT NULL  ,[siteID] VARCHAR(25) NOT NULL  DEFAULT NULL  ,CONSTRAINT [||PRE||mmc_transaction_mmc_transaction_ms_transaction_PRIMARY]  PRIMARY KEY  NONCLUSTERED  ([transactionID])); 
 CREATE  INDEX [||PRE||mmc_transaction_mmc_transaction_ms_transaction_idxcartID] ON [||PRE||mmc_transaction] ([cartID]);
 CREATE  INDEX [||PRE||mmc_transaction_mmc_transaction_ms_transaction_idxOrderIdent] ON [||PRE||mmc_transaction] ([orderIdent]);
 CREATE  INDEX [||PRE||mmc_transaction_mmc_transaction_ms_transaction_idxRemoteID] ON [||PRE||mmc_transaction] ([remoteID]);
 CREATE  INDEX [||PRE||mmc_transaction_mmc_transaction_ms_transaction_idxSiteID] ON [||PRE||mmc_transaction] ([siteID]);

;INSERT INTO [||PRE||mmc_displaytype] (displaytypeid,objectID,package,name,description,settings,isConfigurable,isActive,version,defaults,moduleID)( select N'FA61DC1C-E245-41F8-B69F7763ED3D71C3',N'054F5F6F-2155-4321-9D99D90CA244A5EA',N'cart',N'Cart & Checkout',N'The cart and checkout display objects',NULL,0,1,N'0.5',NULL,N'AE776AA4-93DB-4064-AB59B500D19EB40D');

SET IDENTITY_INSERT [||PRE||mmc_location] ON;

INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 1,N'Alabama',N'AL',N'state',100) union all ( select 2,N'Alaska',N'AK',N'state',100) union all ( select 3,N'Arizona',N'AZ',N'state',100) union all ( select 4,N'Arkansas',N'AR',N'state',100) union all ( select 5,N'California',N'CA',N'state',100) union all ( select 6,N'Colorado',N'CO',N'state',100) union all ( select 7,N'Connecticut',N'CT',N'state',100) union all ( select 8,N'Delaware',N'DE',N'state',100) union all ( select 9,N'District of Columbia',N'DC',N'state',100) union all ( select 10,N'Florida',N'FL',N'state',100) union all ( select 11,N'Georgia',N'GA',N'state',100) union all ( select 12,N'Hawaii',N'HI',N'state',100) union all ( select 13,N'Idaho',N'ID',N'state',100) union all ( select 14,N'Illinois',N'IL',N'state',100) union all ( select 15,N'Indiana',N'IN',N'state',100) union all ( select 16,N'Iowa',N'IA',N'state',100) union all ( select 17,N'Kansas',N'KS',N'state',100) union all ( select 18,N'Kentucky',N'KY',N'state',100) union all ( select 19,N'Louisiana',N'LA',N'state',100) union all ( select 20,N'Maine',N'ME',N'state',100) union all ( select 21,N'Maryland',N'MD',N'state',100) union all ( select 22,N'Massachusetts',N'MA',N'state',100) union all ( select 23,N'Michigan',N'MI',N'state',100) union all ( select 24,N'Minnesota',N'MN',N'state',100) union all ( select 25,N'Mississippi',N'MS',N'state',100) union all ( select 26,N'Missouri',N'MO',N'state',100) union all ( select 27,N'Montana',N'MT',N'state',100) union all ( select 28,N'Nebraska',N'NE',N'state',100) union all ( select 29,N'Nevada',N'NV',N'state',100) union all ( select 30,N'New Hampshire',N'NH',N'state',100) union all ( select 31,N'New Jersey',N'NJ',N'state',100) union all ( select 32,N'New Mexico',N'NM',N'state',100) union all ( select 33,N'New York',N'NY',N'state',100) union all ( select 34,N'North Carolina',N'NC',N'state',100) union all ( select 35,N'North Dakota',N'ND',N'state',100) union all ( select 36,N'Ohio',N'OH',N'state',100) union all ( select 37,N'Oklahoma',N'OK',N'state',100) union all ( select 38,N'Oregon',N'OR',N'state',100) union all ( select 39,N'Pennsylvania',N'PA',N'state',100) union all ( select 40,N'Rhode Island',N'RI',N'state',100) union all ( select 41,N'South Carolina',N'SC',N'state',100) union all ( select 42,N'South Dakota',N'SD',N'state',100) union all ( select 43,N'Tennessee',N'TN',N'state',100) union all ( select 44,N'Texas',N'TX',N'state',100) union all ( select 45,N'Utah',N'UT',N'state',100) union all ( select 46,N'Vermont',N'VT',N'state',100) union all ( select 47,N'Virginia',N'VA',N'state',100) union all ( select 48,N'Washington',N'WA',N'state',100) union all ( select 49,N'West Virginia',N'WV',N'state',100) union all ( select 50,N'Wisconsin',N'WI',N'state',100) union all ( select 51,N'Wyoming',N'WY',N'state',100) union all ( select 52,N'Alberta',N'AB',N'state',100) union all ( select 53,N'British Columbia',N'BC',N'state',100) union all ( select 54,N'Manitoba',N'MN',N'state',100) union all ( select 55,N'New Brunswick',N'NB',N'state',100) union all ( select 56,N'Newfoundland and Labrador',N'NL',N'state',100) union all ( select 57,N'Northwest Territories',N'NT',N'state',100) union all ( select 58,N'Nova Scotia',N'NS',N'state',100) union all ( select 59,N'Nunavut',N'NU',N'state',100) union all ( select 60,N'Ontario',N'ON',N'state',100) union all ( select 61,N'Prince Edward Island',N'PE',N'state',100) union all ( select 62,N'Quebec',N'QC',N'state',100) union all ( select 63,N'Saskatchewan',N'SK',N'state',100) union all ( select 64,N'Yukon Territory',N'YT',N'state',100) union all ( select 128,N'Afghanistan',N'AF',N'country',100) union all ( select 129,N'�land Islands',N'AX',N'country',100) union all ( select 130,N'Albania',N'AL',N'country',100) union all ( select 131,N'Algeria',N'DZ',N'country',100) union all ( select 132,N'American Samoa',N'AS',N'country',100) union all ( select 133,N'Andorra',N'AD',N'country',100) union all ( select 134,N'Angola',N'AO',N'country',100) union all ( select 135,N'Anguilla',N'AI',N'country',100) union all ( select 136,N'Antarctica',N'AQ',N'country',100) union all ( select 137,N'Antigua and Barbuda',N'AG',N'country',100) union all ( select 138,N'Argentina',N'AR',N'country',100) union all ( select 139,N'Armenia',N'AM',N'country',100) union all ( select 140,N'Aruba',N'AW',N'country',100) union all ( select 141,N'Australia',N'AU',N'country',100) union all ( select 142,N'Austria',N'AT',N'country',100) union all ( select 143,N'Azerbaijan',N'AZ',N'country',100) union all ( select 144,N'Bahamas',N'BS',N'country',100) union all ( select 145,N'Bahrain',N'BH',N'country',100) union all ( select 146,N'Bangladesh',N'BD',N'country',100) union all ( select 147,N'Barbados',N'BB',N'country',100) union all ( select 148,N'Belarus',N'BY',N'country',100) union all ( select 149,N'Belgium',N'BE',N'country',100) union all ( select 150,N'Belize',N'BZ',N'country',100) union all ( select 151,N'Benin',N'BJ',N'country',100) union all ( select 152,N'Bermuda',N'BM',N'country',100) union all ( select 153,N'Bhutan',N'BT',N'country',100) union all ( select 154,N'Bolivia',N'BO',N'country',100) union all ( select 155,N'Bosnia and Herzegovina',N'BA',N'country',100) union all ( select 156,N'Botswana',N'BW',N'country',100) union all ( select 157,N'Bouvet Island',N'BV',N'country',100) union all ( select 158,N'Brazil',N'BR',N'country',100) union all ( select 159,N'British Indian Ocean Territory',N'IO',N'country',100) union all ( select 160,N'Brunei Darussalam',N'BN',N'country',100) union all ( select 161,N'Bulgaria',N'BG',N'country',100) union all ( select 162,N'Burkina Faso',N'BF',N'country',100) union all ( select 163,N'Burundi',N'BI',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 164,N'Cambodia',N'KH',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 165,N'Cameroon',N'CM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 166,N'Canada',N'CA',N'country',2)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 167,N'Cape Verde',N'CV',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 168,N'Cayman Islands',N'KY',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 169,N'Central African Republic',N'CF',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 170,N'Chad',N'TD',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 171,N'Chile',N'CL',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 172,N'China',N'CN',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 173,N'Christmas Island',N'CX',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 174,N'Cocos (Keeling) Island',N'CC',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 175,N'Colombia',N'CO',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 176,N'Comoros',N'KM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 177,N'Congo',N'CG',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 178,N'Congo, The Democratic Republic of the',N'CD',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 179,N'Cook Islands',N'CK',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 180,N'Costa Rica',N'CR',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 181,N'C�te d''Ivoire',N'CI',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 182,N'Croatia',N'HR',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 183,N'Cuba',N'CU',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 184,N'Cyprus',N'CY',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 185,N'Czech Republic',N'CZ',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 186,N'Denmark',N'DK',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 187,N'Djibouti',N'DJ',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 188,N'Dominica',N'DM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 189,N'Dominican Republic',N'DO',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 190,N'Ecuador',N'EC',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 191,N'Egypt',N'EG',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 192,N'El Salvador',N'SV',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 193,N'Equatorial Guinea',N'GQ',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 194,N'Eritrea',N'ER',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 195,N'Estonia',N'EE',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 196,N'Ethiopia',N'ET',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 197,N'Faeroe Islands',N'FO',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 198,N'Falkland Islands (Malvinas)',N'FK',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 199,N'Fiji',N'FJ',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 200,N'Finland',N'FI',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 201,N'France',N'FR',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 202,N'French Guiana',N'GF',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 203,N'French Polynesia',N'PF',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 204,N'French Southern Territories',N'TF',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 205,N'Gabon',N'GA',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 206,N'Gambia',N'GM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 207,N'Georgia',N'GE',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 208,N'Germany',N'DE',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 209,N'Ghana',N'GH',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 210,N'Gibraltar',N'GI',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 211,N'Greece',N'GR',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 212,N'Greenland',N'GL',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 213,N'Grenada',N'GD',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 214,N'Guadeloupe',N'GP',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 215,N'Guam',N'GU',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 216,N'Guatemala',N'GT',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 217,N'Guernsey',N'GG',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 218,N'Guinea',N'GN',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 219,N'Guinea-Bissau',N'GW',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 220,N'Guyana',N'GY',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 221,N'Haiti',N'HT',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 222,N'Heard Island and McDonald Islands',N'HM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 223,N'Honduras',N'HN',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 224,N'Hong Kong',N'HK',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 225,N'Hungary',N'HU',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 226,N'Iceland',N'IS',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 227,N'India',N'IN',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 228,N'Indonesia',N'ID',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 229,N'Iran',N'IR',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 230,N'Iraq',N'IQ',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 231,N'Ireland, Republic of (EIRE)',N'IE',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 232,N'Isle of Man',N'IM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 233,N'Israel',N'IL',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 234,N'Italy',N'IT',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 235,N'Jamaica',N'JM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 236,N'Japan',N'JP',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 237,N'Jersey',N'JE',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 238,N'Jordan',N'JO',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 239,N'Kazakhstan',N'KZ',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 240,N'Kenya',N'KE',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 241,N'Kiribati',N'KI',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 242,N'Korea, North',N'KP',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 243,N'Korea, South',N'KR',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 244,N'Kuwait',N'KW',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 245,N'Kyrgyzstan',N'KG',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 246,N'Laos',N'LA',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 247,N'Latvia',N'LV',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 248,N'Lebanon',N'LB',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 249,N'Lesotho',N'LS',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 250,N'Liberia',N'LR',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 251,N'Libya',N'LY',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 252,N'Liechtenstein',N'LI',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 253,N'Lithuania',N'LT',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 254,N'Luxembourg',N'LU',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 255,N'Macao',N'MO',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 256,N'Macedonia (FYROM)',N'MK',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 257,N'Madagascar',N'MG',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 258,N'Malawi',N'MW',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 259,N'Malaysia',N'MY',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 260,N'Maldives',N'MV',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 261,N'Mali',N'ML',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 262,N'Malta',N'MT',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 263,N'Marshall Islands',N'MH',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 264,N'Martinique',N'MQ',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 265,N'Mauritania',N'MR',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 266,N'Mauritius',N'MU',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 267,N'Mayotte',N'YT',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 268,N'Mexico',N'MX',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 269,N'Micronesia, Federated States of',N'FM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 270,N'Moldova',N'MD',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 271,N'Monaco',N'MC',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 272,N'Mongolia',N'MN',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 273,N'Montenegro',N'ME',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 274,N'Montserrat',N'MS',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 275,N'Morocco',N'MA',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 276,N'Mozambique',N'MZ',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 277,N'Myanmar',N'MM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 278,N'Namibia',N'NA',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 279,N'Nauru',N'NR',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 280,N'Nepal',N'NP',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 281,N'Netherlands',N'NL',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 282,N'Netherlands Antilles',N'AN',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 283,N'New Caledonia',N'NC',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 284,N'New Zealand',N'NZ',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 285,N'Nicaragua',N'NI',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 286,N'Niger',N'NE',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 287,N'Nigeria',N'NG',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 288,N'Niue',N'NU',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 289,N'Norfolk Island',N'NF',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 290,N'Northern Mariana Islands',N'MP',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 291,N'Norway',N'NO',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 292,N'Oman',N'OM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 293,N'Pakistan',N'PK',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 294,N'Palau',N'PW',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 295,N'Palestinian Territory, Occupied',N'PS',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 296,N'Panama',N'PA',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 297,N'Papua New Guinea',N'PG',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 298,N'Paraguay',N'PY',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 299,N'Peru',N'PE',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 300,N'Philippines',N'PH',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 301,N'Pitcairn',N'PN',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 302,N'Poland',N'PL',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 303,N'Portugal',N'PT',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 304,N'Puerto Rico',N'PR',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 305,N'Qatar',N'QA',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 306,N'R�union',N'RE',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 307,N'Romania',N'RO',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 308,N'Russian Federation',N'RU',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 309,N'Rwanda',N'RW',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 310,N'Saint Barth�lemy',N'BL',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 311,N'Saint Helena',N'SH',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 312,N'Saint Kitts and Nevis',N'KN',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 313,N'Saint Lucia',N'LC',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 314,N'Saint Martin (French part)',N'MF',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 315,N'Saint Pierre and Miquelon',N'PM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 316,N'Saint Vincent and the Grenadines',N'VC',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 317,N'Samoa',N'WS',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 318,N'San Marino',N'SM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 319,N'Sao Tome and Principe',N'ST',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 320,N'Saudi Arabia',N'SA',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 321,N'Senegal',N'SN',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 322,N'Serbia',N'RS',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 323,N'Seychelles',N'SC',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 324,N'Sierra Leone',N'SL',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 325,N'Singapore',N'SG',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 326,N'Slovakia',N'SK',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 327,N'Slovenia',N'SI',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 328,N'Solomon Islands',N'SB',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 329,N'Somalia',N'SO',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 330,N'South Africa',N'ZA',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 331,N'South Georgia and the South Sandwich Islands',N'GS',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 332,N'Spain',N'ES',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 333,N'Sri Lanka',N'LK',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 334,N'Sudan',N'SD',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 335,N'Suriname',N'SR',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 336,N'Swaziland',N'SZ',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 337,N'Sweden',N'SE',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 338,N'Switzerland',N'CH',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 339,N'Syria',N'SY',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 340,N'Taiwan',N'TW',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 341,N'Tajikistan',N'TJ',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 342,N'Tanzania, United Republic of',N'TZ',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 343,N'Thailand',N'TH',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 344,N'Timor-Leste',N'TL',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 345,N'Togo',N'TG',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 346,N'Tokelau',N'TK',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 347,N'Tonga',N'TO',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 348,N'Trinidad and Tobago',N'TT',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 349,N'Tunisia',N'TN',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 350,N'Turkey',N'TR',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 351,N'Turkmenistan',N'TM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 352,N'Turks and Caicos Islands',N'TC',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 353,N'Tuvalu',N'TV',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 354,N'Uganda',N'UG',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 355,N'Ukraine',N'UA',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 356,N'United Arab Emirates',N'AE',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 357,N'United Kingdom',N'GB',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 358,N'United States',N'US',N'country',1)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 359,N'United States Minor Outlying Islands',N'UM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 360,N'Uruguay',N'UY',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 361,N'Uzbekistan',N'UZ',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 362,N'Vanuatu',N'VU',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 363,N'Vatican City State',N'VA',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 364,N'Venezuela',N'VE',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 365,N'Viet Nam',N'VN',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 366,N'Virgin Islands, British',N'VG',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 367,N'Virgin Islands, U.S.',N'VI',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 368,N'Wallis and Futuna',N'WF',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 369,N'Western Sahara',N'EH',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 370,N'Yemen',N'YE',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 371,N'Zambia',N'ZM',N'country',100)
;INSERT INTO [||PRE||mmc_location] (locationID,name,value,locationType,orderNo)( select 372,N'Zimbabwe',N'ZW',N'country',100);

 SET IDENTITY_INSERT [||PRE||mmc_location] OFF; 

INSERT INTO [||PRE||mmc_merchant] (merchantID,name,isActive,custom1label,custom2label,custom3label,remoteID,package,bean,param1label,param2label,param3label,param4label,param5label,param6label,param7label,param8label,param9label,param1,param2,param3,param4,param5,param6,param7,param8,param9,params,isCurrent)( select N'FCE54C19-212B-4985-9440008E1F2A3F8F',N'PayPal Payments Pro',1,N'paypal.correlationid',N'paypal.avscode',N'paypal.errorcode',NULL,N'paypalpaymentspro',N'paypalpaymentspro.PayPalBean',N'paypal.user',N'paypal.password',N'paypal.signature',N'paypal.url',N'paypal.currencycode',NULL,NULL,NULL,NULL,N'',N'',N'',N'https://api-3t.sandbox.paypal.com/nvp',N'USD',NULL,NULL,NULL,NULL,NULL,1);

INSERT INTO [||PRE||mmc_paymenttype] ([paymentTypeID],[name],[identity],[remoteID],[isActive],[params],[paymentType]) VALUES (N'090C9BC0-D109-4640-95769F4D37ED56F6',N'Master Card',N'mastercard',NULL,1,NULL,N'card')
;INSERT INTO [||PRE||mmc_paymenttype] ([paymentTypeID],[name],[identity],[remoteID],[isActive],[params],[paymentType]) VALUES (N'3796C45B-C496-4F6E-BF7B64BD465EDE47',N'Check',N'check',NULL,0,NULL,N'mail')
;INSERT INTO [||PRE||mmc_paymenttype] ([paymentTypeID],[name],[identity],[remoteID],[isActive],[params],[paymentType]) VALUES (N'3AA8FA18-FC2E-4A2F-93160120AF6402B6',N'Invoice',N'invoice',NULL,1,NULL,N'mail')
;INSERT INTO [||PRE||mmc_paymenttype] ([paymentTypeID],[name],[identity],[remoteID],[isActive],[params],[paymentType]) VALUES (N'3DDB8B78-0467-4279-B6A96C95A8D9F56A',N'Discovery',N'discovery',NULL,0,NULL,N'card')
;INSERT INTO [||PRE||mmc_paymenttype] ([paymentTypeID],[name],[identity],[remoteID],[isActive],[params],[paymentType]) VALUES (N'B01B0186-BEC4-4204-BD970C4B23B03CC3',N'American Express',N'amex',NULL,0,NULL,N'card')
;INSERT INTO [||PRE||mmc_paymenttype] ([paymentTypeID],[name],[identity],[remoteID],[isActive],[params],[paymentType]) VALUES (N'FF41D76E-AC58-4246-B7D92136A9CBEE5A',N'Visa',N'visa',NULL,1,NULL,N'card')

;SELECT * FROM [||PRE||mmc_transaction];